openapi: 3.0.0
info:
  version: 1.0.0
  title: Summary Care Record API
  description: |
    
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="https://digital.nhs.uk/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is initially for use by new market entrant <a href="https://digital.nhs.uk/developer/guides-and-documentation/building-healthcare-software/general-practice/integrating-with-national-services">GP IT foundation system developers</a> with other use cases to follow later.</p></div>            
            </div>
        </div>
    </div>
    
    ## Version
    The current released version of this API is 2.3 while minor updates may be available on PTL environments.

    ## Overview
    Use this API to access or update a patient's [Summary Care Record (SCR)](https://digital.nhs.uk/services/summary-care-records-scr) - an electronic record of important patient information, created from GP medical records. SCRs can be seen and used by authorised staff in other areas of the health and care system involved in the patient's direct care.
    
    This API is currently only approved for use in primary care software, specifically GP software. We hope to make it available for secondary care in the future. You can vote for this on our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/151217/summary-care-record-scr-fhir-api-other-use-cases).

    Also use this API to update a patient's SCR Consent Preference on the Spine ACS and to raise electronic Alerts when:
    * a SCR is accessed without the patient's permission
    and/or
    * the equivalent of Self-Claim Legitimate Relationship is created by an individual, who subsequently accesses the patient's SCR
    * send an SCR alert message, on those occasions when an SCR is accessed without the patient's permission e.g., in an emergency or when the equivalent of Self-Claim Legitimate Relationship is created.
    * update a patient's SCR Consent Preference on the Spine ACS

    You can:
    * get a patient's SCR identifier
    * get a patient's SCR
    * upload a patient's SCR
    * send a privacy alert message, if you have to override a patient's dissent to view their SCR 
    * update a patient's SCR Consent Preference on the Spine ACS
    
    A health or care staff providing direct care to patients must be present and authenticated with an [NHS smartcard or a modern alternative](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/nhs-smartcards-for-developers) to use this API.
    
    ## Who can use this API
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see 'Onboarding' below).
    
    This API is initially for use by new market entrant GP IT developers with other use cases to follow later.

    ## Related APIs
    To use this API, you need the patient's NHS number, which can be retrieved by using the following API:
      - [Personal Demographics Service (FHIR) API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) - use this API to search for patients and retrieve their details.  This API can also be used to update their details in some cases. This is the latest version of the PDS API and is recommended for all new integrators.

    This API has endpoints enabling you to get and set access permissions, the same as the [Access Control Service (ACS) HL7 V3 API](https://digital.nhs.uk/developer/api-catalogue/access-control-service-hl7-v3) which it partly replaces.
    
    ## API status and roadmap
    This API is initially for use by new market entrant GP IT developers with other use cases to follow later.
    
    This API is [in production, beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses), meaning:
    
    - the API is available in our sandbox and integration test environments
    - the API is available for production (private beta) use
    - we might make breaking changes, but only if we cannot avoid it, and we'll give advance notice

    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=all&tag=scr-fhir-api&deleted=0#controls).

    If you have any other queries, [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir) global standard for health care data exchange, specifically to [FHIR R4 (v4.0.1)](https://hl7.org/fhir/r4/), except that it does not support the [capabilities](https://hl7.org/fhir/R4/http.html#capabilities) interaction.

    It includes some country-specific FHIR extensions, which are built against [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), specifically [UK.core.r4.v2 2.0.5](https://simplifier.net/packages/uk.core.r4.v2/2.0.5).

    ## Network access
    This API is available on the internet and indirectly on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    This API has two authorisation methods. The first is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present and authenticated to use it.

    The end user must be:
    - a health or care staff providing direct care to patients
    - strongly authenticated, using either an [NHS smartcard or a modern alternative](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/nhs-smartcards-for-developers) available via [NHS Care Identity Service 2 (NHS CIS2)](https://digital.nhs.uk/services/nhs-identity)

    The API uses OAuth 2.0 to authorise the calling system. It supports the following security patterns:

    - [user-restricted RESTful API - using NHS CIS2 - combined authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-cis2-combined-authentication-and-authorisation)
    - [user-restricted RESTful API - using NHS CIS2 - separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-cis2-separate-authentication-and-authorisation)

    For more details, see [user-restricted APIs](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).

    The second authorisation method is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis) (signed JWT authentication), meaning a few specific API calls can be authorised by the application making the requests. This is typically provided so that GPs can perform batch updates of multiple Summary Care Records without having to log in as a specific user.
    
    The following specific endpoint and method combinations can be used with application-restricted authentication, in addition to user-restricted authentication:
    
    - GET DocumentReference
    - GET Bundle
    - POST Bundle
    
    For more details, see:
    - [application-restricted APIs](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis) and 
    - [application-restricted RESTful APIs - signed with JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ## Environments and testing
    | Purpose                                | Base URL                                            |
    | ---------------------------------------|-----------------------------------------------------|
    | Sandbox                                | `https://sandbox.api.service.nhs.uk/summary-care-record/FHIR/R4`|
    | Integration test                       | `https://int.api.service.nhs.uk/summary-care-record/FHIR/R4`    |
    | Production                             | `https://api.service.nhs.uk/summary-care-record/FHIR/R4`    |
    
    ## NME Testing
    The approach to testing for external developers is as follows.
    
    For sandbox, New Market Entrants (NMEs) should perform Self Testing, followed by Integration Testing which will be available on the Assurance Technical Evidencing. NMEs need to meet these to progress in integration.

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
      - is for early developer testing
      - only covers a limited set of scenarios
      - is stateless, so it does not actually persist any updates
      - is open access, so does not allow you to test authorisation

      For more details on sandbox testing, or to try out the sandbox using our \"Try this API\" feature, see the documentation for each endpoint.

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):

    * is for formal integration testing
    * is stateful, so persists updates
    * includes authorisation, with [smartcard](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/nhs-smartcards-for-developers) and non-smartcard options

    It also includes ready-to-use [summary care record test data](https://digital.nhs.uk/developer/api-catalogue/summary-care-record-fhir/summary-care-record-fhir-api-test-data).

    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).   

    ### Production
    Our [production environment](https://digital.nhs.uk/services/path-to-live-environments):

    * is for formal use in a live environment
    * is stateful, so persists updates
    * includes authorisation, with [smartcard](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/nhs-smartcards-for-developers)
 
    For more information about our Production Environment, contact the [National Service Desk](ssd.nationalservicedesk@nhs.net)

    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it's worth planning well ahead.
    
    As part of this process, you need to demonstrate that you can manage risks and that your software conforms technically with the requirements for this API.
    
    Information on this page might impact the design of your software. For details, see [Onboarding support information](https://digital.nhs.uk/developer/api-catalogue/summary-care-record-fhir/onboarding-support-information).
    
    To understand how our online digital onboarding process works, see [digital onboarding](https://digital.nhs.uk/developer/guides-and-documentation/digital-onboarding).
    
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="https://digital.nhs.uk/binaries/content/gallery/icons/play-circle.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">To get started, sign in or create a <a href="https://onboarding.prod.api.platform.nhs.uk/">developer account</a>, then select 'product onboarding'.</p></div>            
            </div>
        </div>
    </div>
    
    ### Troubleshooting
    
    * After setting up your new application through the NHS Developer Portal and connecting it to the Summary Care Record API, you will need to ensure your application has a valid ASID custom attribute. ITOC support services should be able to ensure your ASID values are setup to use the [QUPC_IN190000UK04](https://data.developer.nhs.uk/dms/mim/4.2.00/Domains/PSIS%20Query/Document%20files/PSIS%20Query%20IM.htm#_Toc_Section_6.2) interaction. This interaction is for access to resources on Personal Spine Information Service (PSIS), the former name of Summary Care Record. If this isn't setup, you may encounter 403 Forbidden errors when accessing records. This can be checked by emailing [itoc.supportdesk@nhs.net](mailto:itoc.supportdesk@nhs.net).
    * ITOC should also be able to apply the GP summary v3 message set to the endpoints for you.
    
    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server
    
    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.
    
    ## Exponential Backoff
    In the event of a transitory error:
    
    * 429 - exceeded application rate limit (5 TPS per application)
    * 500 - internal server error
    * 503 - service unavailable
    * 504 - response timed out
    
    The following retries are recommended:
    
    * Attempt 1: 1 minute after first failure
    * Attempt 2: 30 minutes after attempt 1
    * Attempt 3: 60 minutes after attempt 2
    * Attempt 4: 2 hours after attempt 3
    * Attempt 5: 4 hours after attempt 4
    * Attempt 6: 8 hours after attempt 5
    * Attempt 7: 16 hours after attempt 6
    * If attempt 7 fails, then fail permanently.
    
    ## Support
    The National Integration Adaptors & APIs (NIA) Support team provide a support mailbox to support new market entrants integrating with this adaptor. To raise a support ticket please contact [niasupport@nhs.net](mailto:niasupport@nhs.net)
    
    ## Operations
    Here are the links to the possible SCR operations. These endpoints are for create and consume use cases for GP systems:
    * [Get patient's Summary Care Record](#get-/Bundle)
    * [Upload patient's Summary Care Record](#post-/Bundle)
    * [Get patient's latest Summary Care Record identifier](#get-/DocumentReference)
    * [Update patient's consent to share SCR](#post-/$setPermission)
    * [Send a privacy alert message](#post-/AuditEvent)

  license:
    name: MIT
  contact:
    name: Summary Care Record FHIR API Support
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
x-nhsd-api-platform:
  meta:
    name: Summary Care Record API
    canonical_name: summary-care-record
    short_name: scr
    description: This is a generated template API
    pipeline_name_prefix: "Summary-Care-Record"
servers:
  - url: 'https://sandbox.api.service.nhs.uk/summary-care-record/FHIR/R4'
    description: Sandbox environment
  - url: 'https://int.api.service.nhs.uk/summary-care-record/FHIR/R4'
    description: Integration test environment.
x-spec-publication:
  operation-order:
  - operations:
    - method: GET
      path: /DocumentReference
    - method: GET
      path: /Bundle
    - method: POST
      path: /Bundle
    - method: POST
      path: /AuditEvent
    - method: POST
      path: /$setPermission
paths:
  /Bundle:
    post:
      description: |
        ## Overview
        Use this endpoint to upload the details of patient's Summary Care Record.

        To execute the upload you must provide patient's NHS number.
        In case of an update, before executing the request, latest UUID must be obtained using GET /DocumentReference endpoint
        and set inside the request body.
        
        ## Usage diagram
        ![POST SCR Diagram](https://raw.githubusercontent.com/NHSDigital/summary-care-record-api/various-documentation-changes/specification/components/resources/images/diagram-1.jpg)

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:
        
        | Scenario                          | Request                                           | Response                                                                                                                              |
        | ----------------------------------| ------------------------------------------------- | -------------------- |
        | Happy path                        | `Patient.identifier.value`=`9000000009`           | HTTP Status 201      |
        | No patient's consent to store SCR | `Patient.identifier.value`=`9111231130`           | HTTP Status 403      |
      
      summary: Upload patient's Summary Care Record
      operationId: upload-scr
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/UploadBundle.yaml
            example:
              $ref: components/examples/UploadScrBundle.json
      responses:
        "201":
          description: SCR successfully uploaded
        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Issue severity | Issue code    | Description |
            | ----------- | -------------- | ------------- | --------------------------------------------- |
            | 400         | error          | invalid       | Bad request, error in business logic on the client's side |
            | 401         | error          | forbidden     | Unauthorized, access token missing, invalid or expired |
            | 403         | error          | forbidden     | There's no patient's consent to store SCR |
            | 413         | error          | invalid       | Content too large, request was larger than the server was able to handle. This is a host imposed limitation/error.  |
            | 415         | error          | not-supported | Unsupported Media Type, Content-Type header is invalid or missing. The following header should be sent with the request: `Content-Type: application/fhir+json` |
            | 429         | error          | -             | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: invalid
                    details:
                      text: "[PSIS-30134] - Duplicate event with eventId FFFBB3CF-62F3-11EC-BCD6-024734D13536 and nhsNumber 9111231130."
        "500":
          description: Internal Server Error. A similar message could be triggered for 502 Bad Gateway or any other 5XX error. See the "Errors" section for more details.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcomeInternalServerError.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                        version: 1
                        code: UNKNOWN_ERROR
                        display: Unknown Error
                    diagnostics: "An unknown server-side error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support. (Message ID: rrt-4161241190348351641-b-geu2-4210-928960-20)"
        "503":
          description: Service unavailable. Response may be JSON as per example, or HTML message including the term "503 Service Temporarily Unavailable".
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: transient
                    details:
                      "text": "Code: 503, Display: Service Not Available"
        "504":
          description: |
            The request timed out during processing. This does not imply the request has failed or been rejected.
            Re-send the request using the same `X-Request-ID` value. Wait 5 seconds before the first retried request.
            Where multiple retries are necessary, adopt an exponential back-off approach.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: transient
                    details:
                      text: Request processing timed out. Spine POST + polling GET has timed out
    get:
      description: |
        ## Overview
        Use this endpoint to retrieve the details of a patient's most recent Summary Care Record.

        You must specify the NHS number and the UUID of the latest Summary Care Record of this patient. This UUID should be obtained using the GET /DocumentReference endpoint.

        If you specify an out-of-date UUID, this endpoint returns a Bundle with 0 entries.
        
        ## Usage diagram
        
        ![GET SCR Diagram](https://raw.githubusercontent.com/NHSDigital/summary-care-record-api/various-documentation-changes/specification/components/resources/images/diagram-2.jpg)

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario                         | Request                                                                                                                             | Response                          |
        | -------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------|---------------------------------- |
        | Happy path                       | `composition.identifier`=`FA60BE64-1F34-11EB-A2A8-000C29A364EB` `composition.subject:Patient.identifier`=`9000000009`               | HTTP Status 200 - Full Bundle     |
        | No results                       | `composition.identifier`=`81CC2DA0-8882-11EB-B538-0800200C9A66` `composition.subject:Patient.identifier`=`9000000033`               | HTTP Status 200 - Empty Bundle    |
        | Invalid results                  | `composition.identifier`=`INVALID ID` `composition.subject:Patient.identifier`=`INVALID NHS NUMBER`                                 | HTTP Status 400 - Invalid Request |
        
      summary: Get patient's Summary Care Record
      operationId: get-scr
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - in: query
          name: composition.identifier
          description: Latest Patient's Summary Care Record identifier. Can be obtained using GET /DocumentReference endpoint.
          example: FA60BE64-1F34-11EB-A2A8-000C29A364EB
          required: true
          schema:
            type: string
        - in: query
          name: composition.subject:Patient.identifier
          description: The patient's NHS number. Must be preceded with FHIR identifier (eg."composition.subject:Patient.identifier=https://fhir.nhs.uk/Id/nhs-number|9000000009")
          example: https://fhir.nhs.uk/Id/nhs-number|9000000009
          required: true
          schema:
            type: string

      responses:
        "200":
          description: SCR successfully returned
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/GetScrBundle.yaml
              example:
                $ref: components/examples/GetScrBundle.json
        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Issue severity | Issue code    | Description |
            | ----------- | -------------- | ------------- | --------------------------------------------- |
            | 400         | error          | invalid       | Bad request, error in business logic on the client's side |
            | 401         | error          | forbidden     | Unauthorized, access token missing, invalid or expired |
            | 403         | error          | forbidden     | There's no patient's consent to store SCR |
            | 420         | error          | forbidden     | Business condition related to access control  which prevents the action being performed by PSIS |
            | 429         | error          | -             | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: forbidden
                    details:
                      text: "Code: 420, Display: Business condition related to access control  which prevents the action being performed by PSIS;Code: 30418, Display: [PSIS-30418] - ACF does not permit access to resource"
        "500":
          description: Internal Server Error. A similar message could be triggered for 502 Bad Gateway or any other 5XX error. See the "Errors" section for more details.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcomeInternalServerError.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                        version: 1
                        code: UNKNOWN_ERROR
                        display: Unknown Error
                    diagnostics: "An unknown server-side error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support. (Message ID: rrt-4161241190348351641-b-geu2-4210-928960-20)"
        "503":
          description: Service unavailable. Response may be JSON as per example, or HTML message including the term "503 Service Temporarily Unavailable".
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: transient
                    details:
                      "text": "Code: 503, Display: Service Not Available"
  /DocumentReference:
    get:
      summary: Get patient's latest Summary Care Record identifier
      operationId: get-scr-id
      description: |
        ## Overview
        Use this endpoint to retrieve UUID of patient's latest record.
        The UUID is required to retrieve the Summary Care Record details using GET /Bundle endpoint
        and to update the details of patient's Summary Care Record using POST /Bundle endpoint.
        
        This endpoint also returns patient's consent status in the securityLabel attribute of a successful API response.

        To get the information you must provide patient's NHS number.
        When no NHS Number is supplied in the patient query parameter, 400 HTTP status is returned.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:
        
        | Scenario                          | Request                           | Response                           |
        | ----------------------------------| --------------------------------- | ---------------------------------- |
        | Happy path                        | `nhs-number=9000000009`           | HTTP Status 200 - Full Bundle      |
        | Empty result                      | `nhs-number=9000000033`           | HTTP Status 200 - Empty Bundle     |
        | Invalid results                   | `nhs-number=INVALID NHS NUMBER`   | HTTP Status 400 - Invalid Request  |
        
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
        - in: query
          name: patient
          description: The patient's NHS number. Must be preceded with FHIR identifier (eg."patient=https://fhir.nhs.uk/Id/nhs-number|9000000009")
          required: true
          example: https://fhir.nhs.uk/Id/nhs-number|9000000009
          schema:
            type: string
            
        - in: query
          name: type
          description: General Practice Summary snomed code. Must be equal "type=http://snomed.info/sct|196981000000101"
          required: false
          example: http://snomed.info/sct|196981000000101
          schema:
            type: string
          
        - in: query
          name: _sort
          description: Defines how Patient's SCR list should be sorted in order to retrieve the latest one. The only supported value is _sort=date. If a different value is provided 400 HTTP status will be returned.
          required: false
          example: date
          schema:
            type: string
             
        - in: query
          name: _count
          description: Defines the number of latest patient SCR IDs that could be retrieved. Currently the only supported value is _count=1. If a different value is provided 400 HTTP status will be returned.
          required: false
          example: 1
          schema:
            type: integer
              
      responses:
        "200":
          description: Success response
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/DocumentReferenceBundle.yaml
              example:
                $ref: components/examples/DocumentReferenceBundle.json
        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Issue severity | Issue code    | Description |
            | ----------- | -------------- | ------------- | --------------------------------------------- |
            | 400         | error          | invalid       | Bad request, error in business logic on the client's side |
            | 401         | error          | forbidden     | Unauthorized, access token missing, invalid or expired |
            | 403         | error          | forbidden     | There's no patient's consent to store SCR |
            | 429         | error          | -             | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: forbidden
                    details:
                      text: Invalid access token
        "500":
          description: Internal Server Error. A similar message could be triggered for 502 Bad Gateway or any other 5XX error. See the "Errors" section for more details.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcomeInternalServerError.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                        version: 1
                        code: UNKNOWN_ERROR
                        display: Unknown Error
                    diagnostics: "An unknown server-side error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support. (Message ID: rrt-4161241190348351641-b-geu2-4210-928960-20)"
        "503":
          description: Service unavailable. Response may be JSON as per example, or HTML message including the term "503 Service Temporarily Unavailable".
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: transient
                    details:
                      "text": "Code: 503, Display: Service Not Available"
  /$setPermission:
    post:
      summary: Update patient's consent to share SCR
      operationId: acs
      description: |
        ## Overview
        Use this endpoint to update the Permission to share the GP Summaries

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario                         | Request                                                                      | Response             |
        | -------------------------------- | ---------------------------------------------------------------------------- | -------------------- |
        | Happy path                       | `NHSD-Session-URID`=`555254240100`; `nhsNumber`=`9000000009`                 | HTTP Status 201      |
        | Patient not found                | `NHSD-Session-URID`=`555254240100`; `nhsNumber`=`9111231130`                 | HTTP Status 400      |
        
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/Parameters.yaml
            example:
              $ref: components/examples/SetPermission.json
      responses: 
        "201": 
          description: Permission successfully updated
        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Issue severity | Issue code    | Description |
            | ----------- | -------------- | ------------- | --------------------------------------------- |
            | 400         | error          | invalid       | Bad request, error in business logic on the client's side |
            | 401         | error          | forbidden     | Unauthorized, access token missing, invalid or expired |
            | 413         | error          | invalid       | Content too large, request was larger than the server was able to handle. This is a host imposed limitation/error.  |
            | 415         | error          | not-supported | Unsupported Media Type, Content-Type header is invalid or missing. The following header should be sent with the request: `Content-Type: application/fhir+json` |
            | 429         | error          | -             | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-supported
                    details:
                      text: Content type 'text/plain' not supported
        "500":
          description: Internal Server Error. A similar message could be triggered for 502 Bad Gateway or any other 5XX error. See the "Errors" section for more details.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcomeInternalServerError.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                        version: 1
                        code: UNKNOWN_ERROR
                        display: Unknown Server Side Error
                    diagnostics: "An unknown server-side error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support. (Message ID: rrt-4161241190348351641-b-geu2-4210-928960-20)"

  /AuditEvent:
    post:
      summary: Send a privacy alert message
      operationId: alert
      description: |
        ## Overview
        Use this endpoint to raise an Electronic Alert to an organisation's Privacy Officer(s) when a Care Professional in the same organisation creates a Self-Claim LR or accesses an SCR without the patient's permission.
        
        The following combinations of type and subtype are possible. Note the non-permitted combinations in this list:
        | Requirement Identifier | Alert Type | Alert Type Display       | Alert Sub-Type<br>(“Reason Code”) | Alert Sub-Type (“Reason Display”)  | Business Scenario Notes                    |
        | ---------------------- | ---------- | ------------------------ | --------------------------------- | ---------------------------------- | ------------------------------------------ |
        | MSCA-SCR-103           | 1          | Create LR (Self Claimed) | 1                                 | Access made in the public interest | SCR accessed for legal reasons             |
        | MSCA-SCR-103           | 1          | Create LR (Self Claimed) | 2                                 | Access required by statute         | SCR accessed for legal reasons             |
        | MSCA-SCR-103           | 1          | Create LR (Self Claimed) | 3                                 | Access required by Court Order     | SCR accessed for legal reasons             |
        | MSCA-SCR-103           | 1          | Create LR (Self Claimed) | 4                                 | Self-Claim Emergency Access        | SCR accessed for emergency reasons         |
        | n/a                    | 1          | n/a                      | 5                                 | n/a                                | Not a permitted combination                |
        | MSCA-SCR-103           | 1          | Create LR (Self Claimed) | 6                                 | Other                              | SCR accessed with the patient's permission |
        | MSCA-SCR-105           | 2          | Access Alert             | 1                                 | Access made in the public interest | SCR accessed for legal reasons             |
        | MSCA-SCR-105           | 2          | Access Alert             | 2                                 | Access required by statute         | SCR accessed for legal reasons             |
        | MSCA-SCR-105           | 2          | Access Alert             | 3                                 | Access required by Court Order     | SCR accessed for legal reasons             |
        | n/a                    | 2          | n/a                      | 4                                 | n/a                                | Not a permitted combination                |
        | MSCA-SCR-104           | 2          | Access Alert             | 5                                 | Access made in an emergency        | SCR accessed for emergency reasons.        |
        | n/a                    | 2          | n/a                      | 6                                 | n/a                                | Not a permitted combination                |
        
        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario                         | Request                                  | Response             |
        | -------------------------------- | ---------------------------------------- | -------------------- |
        | Happy path                       | `nhsNumber`=`9000000009`                 | HTTP Status 201      |
        
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/AuditEvent.yaml
            example:
              $ref: components/examples/AuditEvent.json
      responses:
        "201":
          description: Success response
        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Issue severity | Issue code    | Description |
            | ----------- | -------------- | ------------- | --------------------------------------------- |
            | 400         | error          | invalid       | Bad request, error in business logic on the client's side |
            | 401         | error          | forbidden     | Unauthorized, access token missing, invalid or expired |
            | 413         | error          | invalid       | Content too large, request was larger than the server was able to handle. This is a host imposed limitation/error.  |
            | 415         | error          | not-supported | Unsupported Media Type, Content-Type header is invalid or missing. The following header should be sent with the request: `Content-Type: application/fhir+json` |
            | 429         | error          | -             | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: invalid
                    details:
                      text: NHS number missing
        "500":
          description: Internal Server Error. A similar message could be triggered for 502 Bad Gateway or any other 5XX error. See the "Errors" section for more details.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcomeInternalServerError.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                        version: 1
                        code: UNKNOWN_ERROR
                        display: Unknown Error
                    diagnostics: "An unknown server-side error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support. (Message ID: rrt-4161241190348351641-b-geu2-4210-928960-20)"
components:
  parameters:
    BearerAuthorization:
      in: header
      name: Authorization
      description: |
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
        Required in all environments except sandbox.
      required: true
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: |
        A globally unique identifier (GUID) for the request, which we use to trace the request if you contact our helpdesk.

        When contacting the helpdesk and asking them to trace logs in Splunk, please supply the X-Correlation-ID (GIUD) from the request you are attempting to debug.

        Mirrored back in a response header.

        Avoid `.` characters.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    RequestID:
      in: header
      name: X-Request-ID
      required: false
      description: |
        A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests.

        Must be a universally unique identifier (UUID) (ideally version 4).
        If you re-send a failed request, use the same value in this header.
        Mirrored back in a response header.
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068

    RoleID:
      in: header
      name: NHSD-Session-URID
      description: |

        The user role ID (URID) for the current session. Also known as a user role profile ID (URPID).

        In user-restricted access mode if you send this header it must be valid for the logged-in user. See [determine the user's role](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-cis2-combined-authentication-and-authorisation#step-7-determine-the-user-s-role) for guidance.

      required: false
      schema:
        type: string
        pattern: '^[0-9]+$'
        example: '555021935107'
    ContentType:
      in: header
      name: Content-Type
      description: |
        Used to indicate what type of data is actually sent
      required: true
      schema:
        type: string
        example: 'application/fhir+json'
